In [ ]:
# 유니버셜 함수 : 배열의 각원소를 빠르게 처리하는 함수
import numpy as np

arr = np.arange(10)
print (arr)

# 제곱근 구하기
np.sqrt(arr)
# 지수값 구하기 
np.exp(arr)

# 여기서 seed는 랜덤 숫자를 항상 같은 숫자가 나오도록 시작점을 잡아주는 기능을 함
rng = np.random.default_rng(seed=12345)  
data1 = rng.standard_normal(8)
data2 = rng.standard_normal(8)
print (data1)
print (data2)

# 두배열을 비교해 큰값을 return
np.maximum(data1, data2)

arr = rng.standard_normal(7)*5
print (arr)

# 분수를 받아 몫과 나머지를 반환
remainder, whole_part = np.modf(arr)
remainder
whole_part

arr
out = np.zeros_like(arr)
print (out)
a = np.add(arr, 1)
b = np.add(arr, 1, out=out)
print (f"a = {a}")
print (f"b = {b}")
out

In [ ]:
import numpy as np

points = np.arange(-5, 5, 0.01)
xs, ys = np.meshgrid(points, points)
print (xs)
print (ys)

z = np.sqrt(xs ** 2 + ys ** 2)
print (z)

In [ ]:
import matplotlib.pyplot as plt

plt.imshow(z, cmap=plt.cm.gray, extent=[-5, 5, -5, 5])
plt.colorbar()
plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")

In [ ]:
import numpy as np
rng = np.random.default_rng()
arr = rng.standard_normal(6)
print (arr)
arr.sort()
print (arr)

In [ ]:
import numpy as np


x = [[1,2,3], [4,5,6,]]
y = [[1,2], [4,5],[5,6]]

z = np.dot(x, y)
print (z)

In [ ]:
num1 = range(0, 10)
num2 = range(0, 10)

for i in num1:
    for j in num2:
        if ((i + j) == 9): 
            print("[ ,  ]",end = " ")
            continue           
        print ([num1[i],num2[j]], end = " ")
    print ()

In [ ]:
for i in range(0, 6):
    for j in range(0, i):
        if (i <= 0):
            print(" ", end = " ")
            continue
        print ("*", end = " ") 
    print()

In [ ]:
import random
import matplotlib.pylab as plt

p = 0
w = [p]
s = 1000

for _ in range(s) : 
    rand_num = random.randint(0,1)
    
    if rand_num == 1 :
        s1 = 1
    else :
        s1 = -1  

    p += s1
    w.append(p)

plt.plot(w[:100])
plt.show()
    

In [ ]:
import numpy as np

rng = np.random.default_rng(seed=12345)
draws = rng.integers(0, 2, size=1000)
s1 = np.where(draws == 0, 1, -1)
w = s1.cumsum()

w.min()
w.max()
a = (np.abs(w) >= 10).argmax()
print(a)

w = 5000
s = 1000

draws = rng.integers(0, 2, size=(w, s))
s1 = np.where(draws > 0, 1, -1)
w = s1.cumsum(axis=1)
print (w)

print (w.min())
w.max()

h30 = (np.abs(w) >= 30).any(axis=1)
h30
h30.sum()

ct = (np.abs(w[h30]) >= 30).argmax(axis=1)
print (ct)

w = 5000
s = 1000

ct.mean()
draws = 0.25 * rng.standard_normal((w, s))  # 생성할 배열의 크기를 튜플로 받는다.
print (draws)


155
[[  1   2   3 ...  22  23  22]
 [  1   0  -1 ... -50 -49 -48]
 [  1   2   3 ...  50  49  48]
 ...
 [ -1  -2  -1 ... -10  -9 -10]
 [ -1  -2  -3 ...   8   9   8]
 [ -1   0   1 ...  -4  -3  -2]]
-120
[201 491 283 ... 219 259 541]
[[-0.04049737 -0.72203015 -0.25774138 ...  0.42355751 -0.67303006
  -0.41968018]
 [-0.04384188 -0.35375729  0.27860676 ...  0.01100176 -0.00527772
  -0.08297507]
 [ 0.35227417 -0.35383118  0.09818312 ... -0.02725589 -0.04007853
  -0.09849703]
 ...
 [ 0.22455202 -0.12520673 -0.02435565 ... -0.19437209 -0.20666754
   0.16508676]
 [-0.04544783  0.2540093  -0.298138   ...  0.467853    0.03529931
  -0.18926481]
 [-0.10790612 -0.11282332 -0.05788132 ...  0.11783678 -0.03052947
   0.18259634]]
